### ISSUE TITLE
After share a action(plant) the dialog do no close

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [gabeira/Plantare#24]
After click and share an action,  the user see a Toast "Sua boa ação foi compartilhada com sucesso!"
but de dialogue remain open.

**Comment by rmxsantiago** [comment]
Hi Daniel, I can take this issue to try to fix it. I will have a look later on.

**Comment by gabeira** [comment]
As we change the app to donate plants instead of planting, we remove the share option for the moment.

**Comment by gabeira** [comment]
As we change the app to donate plants instead of planting, we remove the share option for the moment.
